<?php
require_once __DIR__.'/events.php';
use Imaginary\{Rules,Engine,RuleConfig};
RuleConfig::configure(['characterBudget'=>1000]);
$cycle=fs('active',[fe('draw','paid_cards'),fe('branch')+['condition'=>'paid_all_hand','then'=>[fe('draw')],'else'=>[]]],1,'chosen');
$cycle['cost']['zone']='hand_equipment';
checkFeedback(Rules::validateBuild(fb([$cycle]))['character']['skills'][0]['cost']['zone']==='hand_equipment','mixed card cost roundtrips validation');
$g=fg([$cycle]);$equipment=fc($g,'a','punch');fa($g,'a',['type'=>'play','card'=>$equipment]);$h1=fc($g,'a','defense');$h2=fc($g,'a','defense');
fa($g,'a',['type'=>'skill','index'=>0,'costCards'=>[$h1,$equipment,$h2]]);
checkFeedback(!$g['players']['a']['equipment']&&count($g['players']['a']['hand'])===4,'three mixed cards paid plus all-hand bonus draws four');
checkFeedback(countMechanicCards($g)===[143,143],'mixed fee preserves every physical card');
$g=fg([$cycle]);$equipment=fc($g,'a','haste');fa($g,'a',['type'=>'play','card'=>$equipment]);$h1=fc($g,'a','defense');$h2=fc($g,'a','defense');
fa($g,'a',['type'=>'skill','index'=>0,'costCards'=>[$h1,$equipment]]);
checkFeedback(count($g['players']['a']['hand'])===3&&in_array($h2,array_column($g['players']['a']['hand'],'uid'),true),'keeping one hand card does not gain all-hand bonus');
$g=fg([$cycle]);$equipment=fc($g,'a','punch');fa($g,'a',['type'=>'play','card'=>$equipment]);
checkFeedback((bool)array_filter(Engine::legalActions($g,'a'),function($a){return $a['action']['type']==='skill';}),'equipment alone can pay a mixed cost');
fa($g,'a',['type'=>'skill','index'=>0,'costCards'=>[$equipment]]);
checkFeedback(count($g['players']['a']['hand'])===1,'zero original hand cards does not qualify for all-hand bonus');
$g=fg([$cycle]);$h1=fc($g,'a','defense');$foreign=fc($g,'b','defense');$before=$g;
rejectFeedback(function()use(&$g,$h1,$foreign){fa($g,'a',['type'=>'skill','index'=>0,'costCards'=>[$h1,$foreign]]);},'cannot pay another player card');
checkFeedback($before===$g,'forged mixed cost rejected atomically');
$handOnly=$cycle;$handOnly['effects']=[fe('draw','paid_hand'),fe('add_mark','paid_equipment')+['key'=>'装备']];
$g=fg([$handOnly]);$equipment=fc($g,'a','punch');fa($g,'a',['type'=>'play','card'=>$equipment]);$h1=fc($g,'a','defense');
fa($g,'a',['type'=>'skill','index'=>0,'costCards'=>[$equipment,$h1]]);
checkFeedback(count($g['players']['a']['hand'])===1&&$g['players']['a']['skillMarks']['装备']===1,'hand/equipment counts are bound separately before paying');
$g=fg([$cycle,fs('before_take_damage',[fe('event_reduce_damage')],1,0,['optional'=>true])]);$equipment=fc($g,'a','treasure');fa($g,'a',['type'=>'play','card'=>$equipment]);
fa($g,'a',['type'=>'skill','index'=>0,'costCards'=>[$equipment]]);
checkFeedback($g['pending']['kind']==='skill_offer'&&!$g['players']['a']['hand'],'equipment fee backlash suspends the paid skill before it draws');
$g=json_decode(json_encode($g),true);completeMechanic($g,'a','accept');
checkFeedback(count($g['players']['a']['hand'])===1&&$g['players']['a']['marks']['neutral']===1,'fee event reconnect resumes already-bound paid count once');
checkFeedback(countMechanicCards($g)===[143,143],'equipment backlash fee conserves cards');
RuleConfig::configure(null);echo 'PASS '.$checks.' cumulative cost assertions'.PHP_EOL;
